// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      // case TargetPlatform.iOS:
      //   return ios;
      // case TargetPlatform.macOS:
      //   throw UnsupportedError(
      //     'DefaultFirebaseOptions have not been configured for macos - '
      //     'you can reconfigure this by running the FlutterFire CLI again.',
      //   );
      // case TargetPlatform.windows:
      //   throw UnsupportedError(
      //     'DefaultFirebaseOptions have not been configured for windows - '
      //     'you can reconfigure this by running the FlutterFire CLI again.',
      //   );
      // case TargetPlatform.linux:
      //   throw UnsupportedError(
      //     'DefaultFirebaseOptions have not been configured for linux - '
      //     'you can reconfigure this by running the FlutterFire CLI again.',
      //   );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyACkWbbEc1fvqI6KMiWJDMTzf2Hhi3sXrw",
    authDomain: "doctor-appointment-app-f73f5.firebaseapp.com",
    projectId: "doctor-appointment-app-f73f5",
    storageBucket: "doctor-appointment-app-f73f5.firebasestorage.app",
    messagingSenderId: "772248017636",
    appId: "1:772248017636:web:f4accb051e6345e9796af1",
    measurementId: "G-FVHN2STMZY",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACkWbbEc1fvqI6KMiWJDMTzf2Hhi3sXrw',
    appId: '1:772248017636:web:ca23fb1344ecaae7796af1',
    messagingSenderId: '772248017636',
    projectId: 'doctor-appointment-app-f73f5',
    storageBucket: 'doctor-appointment-app-f73f5.firebasestorage.app',
  );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyDqCVsA1-xlHgNDhtSHpvI4qRM98zVBgOA',
  //   appId: '1:545059185697:ios:45f15c5756e4e9eda9af60',
  //   messagingSenderId: '545059185697',
  //   projectId: 'healthful-dev',
  //   storageBucket: 'healthful-dev.firebasestorage.app',
  //   iosBundleId: 'com.hifah.healthful',
  // );
}
